#include<iostream>
using namespace std;
#include<conio.h>
int main()
{
    int n,j,i,t=1,u,k,l;
    u=6;
    cout<<"calender of 2000 to 2099\n";
    cout<<"enter the year to view calendar\n";
    cin>>n;
    for(i=2001;i<=n;i++)
    {
        if(i%4==1)
            u=u+2;
        else
            u=u+1;
    }
    if(u>7)
    {
        u=u%7;
    }
    cout<<"january:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
    for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    if(n%4==0)
        k=30;
    else
        k=29;
    cout<<"febuary:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
     for(i=1;i<=6;i++)
    {
        if(t>=k)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==k)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;

    cout<<"march:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
      for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"april:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
  for(i=1;i<=6;i++)
    {
        if(t>=31)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==31)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"may:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
   for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;

    cout<<"june:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
     for(i=1;i<=6;i++)
    {
        if(t>=31)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==31)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"july:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
     for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"august:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
  for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"september:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
  for(i=1;i<=6;i++)
    {
        if(t>=31)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==31)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"october:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
   for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"november:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
  for(i=1;i<=6;i++)
    {
        if(t>=31)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==31)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    t=1;
    u=j;
    cout<<"december:\nmon\ttue\twed\tthu\tfri\tsat\tsun\n";
      for(i=1;i<=6;i++)
    {
        if(t>=32)
            break;
        else
        {
        for(j=1;j<=7;j++)
        {
            if(j>=u)
            {
                if(t==32)
                break;
            cout<<t;
            t++;
            }
            cout<<"\t";
        }
        u=1;
        cout<<"\n";
    }
    }
    getch();
}
